POST https://iam.ru-moscow-1.hc.sbercloud.ru/v3/auth/tokens
Content-Type: application/json

{
  "auth": {
    "identity": {
      "methods": [
        "password"
      ],
      "password": {
        "user": {
          "name": "hackathon103",
          "password": "BreakingCode",
          "domain": {
            "name": "hackathon103"
          }
        }
      }
    },
    "scope": {
      "project": {
        "id": "0b9655338780268d2f34c00a8a7a9aea" //Obtain your project ID on the My Credentials page.
      }
    }
  }
}

###